# Generated by Django 2.1.5 on 2019-10-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20191007_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuprice',
            name='topping_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
