# Generated by Django 2.1.5 on 2019-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20191008_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Cart'),
        ),
    ]
