# Generated by Django 2.1.5 on 2019-10-08 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20191008_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuprice',
            name='topping_qty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Topping_qty'),
        ),
        migrations.AlterField(
            model_name='topping_qty',
            name='quantity',
            field=models.IntegerField(max_length=64),
        ),
    ]
