# Generated by Django 2.1.5 on 2019-10-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20191008_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuprice',
            name='topping_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
