# Generated by Django 2.1.5 on 2019-10-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20191010_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_list',
            old_name='current',
            new_name='is_current',
        ),
    ]
