# Generated by Django 2.1.5 on 2019-10-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_auto_20191010_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_size',
            field=models.BooleanField(default=False),
        ),
    ]
