# Generated by Django 2.1.5 on 2019-10-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_category_custom_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='custom_exta',
            new_name='custom_extra',
        ),
    ]
